version: "3.2"

services:
  master:
    image: redis:5.0.5-alpine

  slave:
    image: redis:5.0.5-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master

  sentinel:
    build: ./sentinel
    environment:
      SENTINEL_DOWN_AFTER: 5000
      SENTINEL_FAILOVER: 5000
      REDIS_MASTER_NODE: redis-master
    links:
      - master:redis-master
      - slave
